version: "3"
services:
  postgresdb:
    image: postgres
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tweetdb
      - POSTGRES_PASSWORD=1234
